### ISSUE TITLE
Feature request: getting cue-id as variable

### ISSUE THREAD

**Issue by andik2000** [bitfocus/companion-module-imimot-mitti#17]
I want to show the ID of a cue in a button, instead of the long file name. There is only $currentCueName.
Something like $currentCueID and $selectedCueID etc. would be great.

Thanks,
Andi

**Comment by bryce-seifert** [comment]
This should be pretty simple on the Companion side, but we would need to get that info from Mitti as OSC feedback. I've asked Tamás on Facebook if it's possible to add these.
