### ISSUE TITLE
EHOSTUNREACH error crashes Companion when using Mitti module

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-imimot-mitti#3]
**Describe the bug**
Companion intermittently locks up and throws a "EHOSTUNREACH" error when using a command from the Mitti module.

**To Reproduce**
1. Connect a computer using Mitti
2. Add the Mitti module and establish a connection
3. Create a button utilizing the Mitti commands (some that this has happened with are Play and Jump to Cue with Name)
4. In certain circumstances, error will occur

**Expected behavior**
Command is received properly, OR if it fails and Companion doesn't completely crash.

**Screenshots**
This is the Javascript error that is returned.
![IMG_0454](https://user-images.githubusercontent.com/50299051/68980627-a1effc80-07c6-11ea-97e3-54795f3fd3a8.jpg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari, Firefox
 - Version 2.0 734cd00

**Comment by josephdadams** [comment]
Transferred to the Mitti module. If this ends up being a broader bug from that module, we can transfer it back to the main repo.

**Comment by bryce-seifert** [comment]
@josephdadams Just confirmed that this is also happening with the Generic OSC module. So maybe this is OSC related, since Mitti also uses OSC.

**Comment by josephdadams** [comment]
@bryce-seifert can you reproduce it on another machine?

**Comment by JeffreyDavidsz** [comment]
Is there something listening to that port? This error could come when a bad or no connection is made. So first check ping, if that works check the port number for mitti

**Comment by bryce-seifert** [comment]
@josephdadams Yes, I have been able to reproduce on two different set-ups.
@JeffreyDavidsz I think that bad/ no connection is definitely what's happening. My question would be: is there a way to capture this error so it just get's caught in the logs and doesn't throw the larger EHOSTUNREACH Javascript error that crashes the whole program?

I notice that both Mitti and the OSC instance as long as the IP address is valid, say "OK" not matter the status of the connection. Whereas other instances do a "Checking..." step. Is that something that is possible to integrate?

**Comment by JeffreyDavidsz** [comment]
Yes I believe there is a try catch for this, are you on 2.0?

**Comment by bryce-seifert** [comment]
@JeffreyDavidsz Yes, I'm in the latest build (90725f8) and still getting the EHOSTUNREACH error there
