### ISSUE TITLE
Clip Level Variable Calls

### ISSUE THREAD

**Issue by progressmedia** [bitfocus/companion-module-imimot-mitti#33]
@bryce-seifert thank you so much for what you've done to date so far on the Mitti integration. It's great! I'm wondering if you'd be interested in expounding on your creation of available variables within the module. What I'm most interested in is whether or not the clip has audio enabled as a variable, so I could pinpoint what audio issues I'm having if I have live no-audio problems while on air, if I could quickly glance down at the streamdeck, I could rule out that it's not a mitti toggle on air. 

I am thinking it could be something like $(mitti:currentCueAudiostate) with a binary mute or unmute.  
![image](https://github.com/bitfocus/companion-module-imimot-mitti/assets/117510714/86e51547-62cf-4093-a5e7-a589963a5d33)

That would represent the state of the toggled 

![image](https://github.com/bitfocus/companion-module-imimot-mitti/assets/117510714/32915df7-97ed-4907-bf59-156987ac535f)

**Comment by bryce-seifert** [comment]
The current cue audio variable, as well as status variables for the other current cue options (pause at beginning, loop, etc) have been added with https://github.com/bitfocus/companion-module-imimot-mitti/commit/4a75de3518924dac410b7ee5a8eef177e0797b9f and should be in beta soon!

**Comment by progressmedia** [comment]
Amazing! Awesome, will test it when I see it live.
