### ISSUE TITLE
When you connect to a mac on the network it does not show the time or titles

### ISSUE THREAD

**Issue by lopertyur** [bitfocus/companion-module-imimot-mitti#39]
I have mitti open on a mac on my local network, and it doesn't show the remaining time or the name of the clip, but when I open it on my own mac it does, I've tried several things regarding the firewall, file sharing, etc. But nothing seems to work, so I'm thinking it might be some component error. Everything else works very well, play, next, etc.

**Comment by bryce-seifert** [comment]
Do the feedbacks or any other variables work? Just trying to gauge if it's just those two listed that are working, or nothing is working.

**Comment by lopertyur** [comment]
Yes, everything else works, only the variables that request information for the time left, names of clip, etc. do not work on the network.

**Comment by bryce-seifert** [comment]
Have you set the IP address of the networked Mac in the Mitti settings?
<img width="352" alt="Screenshot 2023-09-17 at 5 28 01 PM" src="https://github.com/bitfocus/companion-module-imimot-mitti/assets/50299051/3f4f39f4-c323-46be-be6b-2e2e5c406c74">

**Comment by lopertyur** [comment]
Yes, otherwise it would be impossible for the rest to work, such as play, pause, next, etc. I tried changing the port, setting a fixed IP address, among other things, but the variables never worked, but everything else did.

**Comment by bryce-seifert** [comment]
It's possible for the actions (play, pause, next, etc.) to work, but for the OSC Feedback to not work in configured improperly.
The fact that it works on the local machine leads me to believe something in the network or configuration is not working.

Just to verify, are both your companion / mitti settings configured as follows?
<img width="1093" alt="Screenshot 2023-09-18 at 6 22 44 PM" src="https://github.com/bitfocus/companion-module-imimot-mitti/assets/50299051/ce948bf5-cbfb-47b1-a0cf-d35b5d880a94">


What version of Companion and Mitti are you using?

**Comment by lopertyur** [comment]
You are absolutely right, I have been wrong. I don't know why I got so confused, mushcas thanks for your answers

**Comment by bryce-seifert** [comment]
No problem! Let me know if you run into any other issues.
