### ISSUE TITLE
Mitti, Dynamic Variables and feedback for individual cues 

### ISSUE THREAD

**Issue by pete10uk** [bitfocus/companion-module-imimot-mitti#8]
**Describe the feature**
The dynamic variables available work great for using Mitti as a sequence of files. Companion adds the ability to trigger individual files like a cart player. What would be great is to have dynamic variables specific to numbered cues, to pull the cue name on a given cue number not just the current playing cue, pull the cue length of a given cue and pull feedback (playing / paused / selected) for a cue not just the play/pause status of Mitti.

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
The would give the ability to use Mitti as a video cart machine even without being able to see the mitti interface.

**Comment by E2SLLC** [comment]
It looks like Imimot added OSC feed back to retrieve the Cue Name from the playlist, if I'm reading this from the most current beta correctly:

Added /mitti/{CueNumber}/cueName OSC feedback

**Comment by bryce-seifert** [comment]
@E2SLLC Yes, I've been working with the dev over there to get all the components needed for this. Hope to have it in the beta soon

**Comment by bryce-seifert** [comment]
Initial support for this is now in the [Companion betas](https://bitfocus.io/companion/download/builds/).

Right now, only the only addition is the cueName variable for each cue. After some testing, I'll work on the additional requests

**Comment by piedrola** [comment]
Wuhu! 2.0 which came with todays beta is working great on my end Bryce, thank you!

**Comment by bryce-seifert** [comment]
@piedrola Glad to hear it! Let me know if anything comes up.

I'm going to close this, as I've implemented play / selected feedbacks.

And currently there's no way to get cut length for a specific cue from Mitti, but if that gets added I'll implement that
