### ISSUE TITLE
/selectedCueName - feature request

### ISSUE THREAD

**Issue by philippkaiser00** [bitfocus/companion-module-imimot-mitti#9]
In the new Mitti version 1.5.13 the OSC feedback message "/selectedCueName" was added. Can you please include this in the module and add it as a text variable?

Thanks!

**Comment by bryce-seifert** [comment]
Working on adding it with https://github.com/bitfocus/companion-module-imimot-mitti/pull/10

**Comment by bryce-seifert** [comment]
Implemented with the merge of https://github.com/bitfocus/companion-module-imimot-mitti/pull/10
